1594237203.570 : radical.entk.appmanager.0000 : 4035  : 123145406189568 : ERROR    : Unknown error in synchronizer: %s.                                     Terminating thread
Traceback (most recent call last):
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 866, in _synchronizer
    self._synchronizer_work()
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 910, in _synchronizer_work
    method_frame, props, body = mq_channel.basic_get(queue=qname_t2s)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_get
    self._basic_getempty_result.is_ready)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 477, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "TimeoutError(60, 'Operation timed out')")
