1594237203.487 : radical.entk.task_manager.0000 : 4168  : 4452212160 : ERROR    : Error in task execution: (-1, "TimeoutError(60, 'Operation timed out')")
Traceback (most recent call last):
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 168, in _tmgr
    mq_channel.basic_get(queue=pending_queue[0])
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_get
    self._basic_getempty_result.is_ready)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 477, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "TimeoutError(60, 'Operation timed out')")
1594237203.491 : radical.entk.task_manager.0000 : 4168  : 4452212160 : ERROR    : task_manager.0000 failed with (-1, "TimeoutError(60, 'Operation timed out')")
Traceback (most recent call last):
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 168, in _tmgr
    mq_channel.basic_get(queue=pending_queue[0])
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_get
    self._basic_getempty_result.is_ready)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 477, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "TimeoutError(60, 'Operation timed out')")
