1594229592.742 : radical.entk.resource_manager.0000 : 3551  : 4349246912 : ERROR    : Resource request submission failed
Traceback (most recent call last):
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 171, in _submit_resource_request
    self._pilot = self._pmgr.submit_pilots(pdesc)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/pilot/pilot_manager.py", line 565, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/pilot/compute_pilot.py", line 100, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(pilot)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/pilot/session.py", line 774, in _get_resource_sandbox
    shell = self.get_js_shell(resource, schema)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/pilot/session.py", line 820, in get_js_shell
    shell = rsup.PTYShell(js_url, self)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/saga/utils/pty_shell.py", line 246, in __init__
    interactive=self.interactive)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/saga/utils/pty_shell_factory.py", line 207, in initialize
    self._initialize_pty(info['pty'], info)
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/saga/utils/pty_shell_factory.py", line 428, in _initialize_pty
    raise ptye.translate_exception (e) from e
  File "/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/saga/utils/pty_shell_factory.py", line 301, in _initialize_pty
    raise rse.NoSuccess("Could not detect shell prompt (timeout)")
radical.saga.exceptions.NoSuccess: Could not detect shell prompt (timeout) (/Users/abdullahghani/myenv/lib/python3.7/site-packages/radical/saga/utils/pty_shell_factory.py +301 (_initialize_pty)  :  raise rse.NoSuccess("Could not detect shell prompt (timeout)"))
